import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="ms:mx-5 mt:mx-8 lg:mx-10">
        <Header />
        <main className="before:content-bg_Line">{children}</main>
      </body>
    </html>
  );
}
